source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.0.beta1'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

gem 'mongoid', github: 'mongoid/mongoid'
gem 'devise'
gem 'anjlab-bootstrap-rails', :require => 'bootstrap-rails',
                              :github => 'anjlab/bootstrap-rails',
                              :branch => '3.0.0'

gem 'cancan'
gem 'rolify', :github => 'EppO/rolify'
gem 'carrierwave', :github => "jnicklas/carrierwave"
gem 'carrierwave-mongoid', :require => 'carrierwave/mongoid'
gem 'mongoid-grid_fs', github: 'ahoward/mongoid-grid_fs'
gem 'rmagick'
gem 'guard'
gem 'guard-rails'
gem 'mongoid_slug', github: 'digitalplaywright/mongoid-slug'
gem 'impressionist', github: 'charlotte-ruby/impressionist'
gem 'haml'
gem "haml-rails"
gem "nested_form"
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'
gem 'mustache-rails', :require => 'mustache/railtie'
gem "ckeditor", :github => "galetahub/ckeditor"
gem 'awesome_nested_set' # or any similar gem (gem 'nested_set')
gem "the_sortable_tree", "~> 2.3.0"
gem "font-awesome-rails", github: "bokmann/font-awesome-rails"
gem 'dalli'
gem 'mini_magick'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development
# Use debugger
# gem 'debugger', group: [:development, :test]
gem 'puma'
